version: '3'

services:
  web:
    container_name: web
    image: chatgpt_frontend
    ports:
      - 8080:80
    depends_on: 
      - api
  api:
    container_name: api
    image: chatgpt_backend
    expose: 
       - 8077
    ports:
       - 8077:8077
    environment:
        - OPENAI_API_KEY=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
    
